
server:
    node: harmonyhub
    name: HarmonyHub Server

FamilyRoom:
    name: HarmonyHub FamilyRoom
    host: 192.168.86.75

MasterBedroom:
    name: HarmonyHub MasterBedroom
    host: 192.168.86.80
