
server:
    node: harmonyhub
    name: HarmonyHub Server

MasterBedroom:
    name: HarmonyHub MasterBedroom
    host: 192.168.86.80

FamilyRoom:
    name: HarmonyHub FamilyRoom
    host: 192.168.86.75
